name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - bode-dev

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Existing Files on Server
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: "*"  # Deletes all files in the root directory
          remoteDirectories: "public_html/*"  # Deletes all files and subdirectories within public_html
          workingDir: "/public_html"
          ignoreSSL: "1"

      - name: Upload New Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/deploy.yml
