name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - bode-dev

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Existing Files on Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./empty-dir/
          server-dir: public_html/  # Ensure this ends with a slash
          exclude: '**'  # Exclude all files to perform a delete operation
          dangerous-clean-slate: true

      - name: Upload New Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/  # Ensure this ends with a slash
          exclude: |
            **/.git*
            **/.git*/**
            **/deploy.yml
