name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - bode-dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
        run: |
            lftp -e "
            set ssl:verify-certificate no;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
            mirror -R ./ public_html/; # Upload directly to the public_html folder
            bye
            "


